baseURL = "https://hcwflustudy.com/"
languageCode = "en-us"
title = "HCW Flu Study"
theme = "LoveIt"

[params]
  # LoveIt theme version
  version = "0.2.X"
  description = "HCW Flu Study site"

[menu]
  [[menu.main]]
    identifier = "Reports"
    pre = ""
    name = "Reports"
    url = "/shinyreports/"
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "New reports"
    pre = ""
    name = "New reports"
    url = "https://reports.hcwflustudy.com"
    title = ""
    weight = 1
